# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/98_Efficiency_syncmap.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/98_Efficiency_syncmap.ipynb 2
import pandas as pd

import numpy as np
import math
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import DBSCAN
from scipy.spatial import distance
from scipy.stats import entropy
from sklearn.metrics import normalized_mutual_info_score, pairwise_distances
from tqdm import tqdm
import copy
from collections import deque
from sklearn.manifold import TSNE

import sys
# sys.path.insert(0, '../')
# 如果没有 pip install -e . 下面一行就不会成功
from .utility import OverlapChunkTest1, to_categorical, compute_combi_dist, reduce_dimension_with_tsne, create_trace_plot, labels2colors

from .processor import GraphProcessor, WorkingMemProcessor, Readout
from scipy.stats import wasserstein_distance

from fastcore.utils import *

import time
import warnings
from joblib import Parallel, delayed
np.set_printoptions(suppress=True)  # disable scientific notation
# from plotly.subplots import make_subplots
# import plotly.graph_objs as go
# import fastcore.all as fc  # patch会报错
# from ipywidgets import widgets
# from IPython.display import display
